### ISSUE TITLE
can i disable broadcast?

### ISSUE THREAD

**Issue by avsba001** [thedunston/bash_cli_zt#1]
sorry, i did't find how to do。

**Comment by thedunston** [comment]
Hey, sorry for the late reply, though this is a question for the ZeroTier developers.

**Comment by avsba001** [comment]
okey ，thanks，i thought script can to do this..

**Comment by thedunston** [comment]
Oh, I see what you're asking.  Sorry, the original question was broad.  Currently, the ACLs with my program are very limited.  Another good project that has a nice GUI and the full suite of ACLs is zero-ui (https://github.com/dec0dOS/zero-ui).  It allows for self-hosting too.

**Comment by avsba001** [comment]
ahaha, my bad, actually i like CLI control with my machine use your project, Let me learn a lot to optimize tcp，
Hope your project is getting stronger. i need to see other project~
